language: node_js
node_js:
   - 0.6

before_install:
  - sudo apt-get install gsl-bin libgsl0-dev libjpeg62 build-essential libgtk2.0-dev libjpeg62-dev libtiff4-dev libjasper-dev libopenexr-dev cmake python-dev python-numpy libtbb-dev libeigen2-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev libcv-dev
